# This workflow build project and test correctness of the league data
# author: Imrihil

name: Build a project and test league data

on:
  workflow_dispatch:

jobs:
  build-and-test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Test
      run: dotnet test tests/TMLeague.Tests -c Release --logger trx --results-directory "TestResults-7.x"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-7.x
        path: TestResults-7.x
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ failure() }}