# This workflow import and commit games
# author: Imrihil

name: Import and commit games

on:
  workflow_dispatch:
    inputs:
      fetch-finished-divisions:
        description: fetch finished divisions
        required: false
        default: false
      fetch-finished-games:
        description: fetch finished games
        required: false
        default: false
      league:
        description: league id
        required: false
        default: ''
      season:
        description: season id
        required: false
        default: ''
      division:
        description: division id
        required: false
        default: ''
  schedule:
    - cron: '51 5,8,11,14,17,20 * * *'

jobs:
  import-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    
    - name: Run TMGameImporter
      run: dotnet run --project src/TMGameImporter/TMGameImporter.csproj -c Release
           --BaseLocation src/TMLeague/wwwroot/data
           --FetchFinishedDivisions ${{ github.event.inputs.fetch-finished-divisions || false }}
           --FetchFinishedGames ${{ github.event.inputs.fetch-finished-games || false }}
           --League "${{ github.event.inputs.league }}"
           --Season "${{ github.event.inputs.season }}"
           --Division "${{ github.event.inputs.division }}"

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Games imported automatically
        title: Games imported automatically
        branch: feature/games-import
        delete-branch: true

    #- name: Approve Pull Request
    #  uses: juliangruber/approve-pull-request-action@v2.0.0
    #  with:
    #    github-token: ${{ secrets.APPROVER_TOKEN }}
    #    number: ${{ steps.create-pr.outputs.pull-request-number }}
    #    repo: juliangruber/approve-pull-request-action # optional

    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.create-pr.outputs.pull-request-number }}
        method: squash