# This workflow import games, commit them and deploy the project to GitHub Pages branch
# author: Imrihil

name: Import games and deploy to GitHub Pages branch

on:
  workflow_dispatch:
    inputs:
      fetch finished divisions:
        description: Should be set to true when already fetched division results needs to be recalculated
        required: false
        default: false
      fetch finished games:
        description: Should be set to true when already fetched and finished games need to be reimported
        required: false
        default: false
      league:
        description: The name of the league to be imported
        required: false
        default: ''
      season:
        description: The name of the season to be imported
        required: false
        default: ''
      division:
        description: The name of the division to be imported
        required: false
        default: ''
  schedule:
    - cron: '51 5,8,11,14,17,20 * * *'

jobs:
  import-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    
    - name: Run TMGameImporter
      run: dotnet run --project src/TMGameImporter/TMGameImporter.csproj -c Release --BaseLocation src/TMLeague/wwwroot/data
           --FetchFinishedDivisions ${{ INPUT_FETCH_FINISHED_DIVISIONS }} --FetchFinishedGames ${{ INPUT_FETCH_FINISHED_GAMES }}
           --League "${{ INPUT_LEAGUE }}" --Season "${{ INPUT_SEASON }}" --Division "${{ INPUT_DIVISION }}"

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Games imported automatically
        title: Games imported automatically
        branch: feature/games-import
        delete-branch: true

    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v2.0.0
      with:
        github-token: ${{ secrets.APPROVER_TOKEN }}
        number: ${{ steps.create-pr.outputs.pull-request-number }}
        repo: juliangruber/approve-pull-request-action # optional

    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.create-pr.outputs.pull-request-number }}
        method: squash

    # publishes Blazor project to the release-folder
    - name: Publish TMLeague
      run: dotnet publish src/TMLeague/TMLeague.csproj -c Release -o release --nologo

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot