# This workflow will deploy the project to GitHub Pages branch
# For more information see: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

name: Import games and commit to master

# Run workflow on every push to the master branch
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5,8,11,14,17,20 * * *'

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2

    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    
    - name: Run TMGameImporter
      run: dotnet run --project src/TMGameImporter/TMGameImporter.csproj -c Release --BaseLocation src/TMLeague/wwwroot/data

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
